### PR TITLE
Problem: Can't launch kernels because runtime dir doesn't exist!

### PR DESCRIPTION
**Pull request by jdfreder**
Sln:  Create the directory if it doesn't exist.

### CODE REVIEW

**Comment by ivanov** [comment]
:bike: :shell:

**Comment by rgbkrk** [comment]
Great! We definitely need this and may want a Jupyter init package of sorts to handle creating the runtime directory as well as the kernels directory (user data dir).

**Comment by rgbkrk** [comment]
Before activating on my potential overengineering for an init package, a small change here would be asynchronous directory check and creation.

**Comment by rgbkrk** [comment]
Loved that bike shell btw. :wink:

**Pull request merged**
