### PR TITLE
[WIP] Lifecycle of a kernel

### PR DESCRIPTION
**Pull request by rgbkrk**
This is one helper method of many that are possible for killing.

Some will want a nice soft kill, sometimes you want a hard kill, sometimes you want to tell the kernel to politely shut down (using the messaging spec), etc. This one is a hard fast shut down.

Open to discussion.

### CODE REVIEW

**Comment by jdfreder** [comment]
Seems the hard kill is trivial.  Wouldn't it make more sense to implement the shutdown request since that is the most complex shutdown method?

**Comment by jdfreder** [comment]
Also, could you add a simple unit test?

**Comment by rgbkrk** [comment]
Definitely. As I work on the build-your-own-repl guide I'll be coming back to this.

**Comment by jdfreder** [comment]
Actually the shutdown request should be a helper method in the enchannel repo I think

**Comment by jdfreder** [comment]
Related https://github.com/nteract/enchannel/pull/9

**Comment by rgbkrk** [comment]
I feel like you've already replaced what I've done here right @jdfreder? Should I close this?

**Comment by rgbkrk** [comment]
This is replaced by the other enchannel shutdown bits I think.

I'll leave it up to Jon to revisit, I don't need this branch any more.

**Pull request closed without merging**
